services:
  - type: web
    name: bot-roleta
    env: python
    plan: free
    runtime: python
    buildCommand: |
      echo "python-3.11.9" > runtime.txt
      pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
